# Generated by Django 3.1.7 on 2021-03-28 02:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ffGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameTitle', models.CharField(max_length=255)),
                ('gameReleaseDate', models.DateField()),
                ('gameReleasePlatform', models.TextField()),
                ('gameSummary', models.TextField()),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='ffReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewTitle', models.CharField(max_length=255)),
                ('reviewDate', models.DateField()),
                ('reviewBody', models.TextField()),
                ('reviewRating', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffreviews.ffgame')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
